### ISSUE TITLE
Got blocked for me

### ISSUE THREAD

**Issue by Rellyjell** [DotLYHiyou/Blackout#3]
Hello DotLYHiyou, this website got blocked for my school and I was wondering if you could add some more links to this website. If you can, I would really appreciate it. If you can't add more links, that's ok.

**Comment by DotLYHiyou** [comment]
I am working on that. Thanks for the heads up.

**Comment by DotLYHiyou** [comment]
You can also deploy it yourself with Vercel.

**Comment by DotLYHiyou** [comment]
I added more links, your welcome!

**Comment by DotLYHiyou** [comment]
they are in the readme
